sudo: required

services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.11.2-0~trusty
        - DOCKER_COMPOSE_VERSION=1.8.0-rc1
        - SERVICE=ethwallet

before_install:
  # Clone `deluge` project
  - git clone --recursive https://github.com/absortium/deluge.git
  - pushd deluge

  # Create mock .sensitive
  - ./useful/create_mock_sensitive.sh

  # list docker-engine versions
  - apt-cache madison docker-engine

  # Upgrade docker-engine to specific version
  - ./useful/upgrade_docker_engine.sh

  # Upgrade docker-compose to specific version
  - ./useful/upgrade_docker_compose.sh

  # Check docker and docker-compose versions
  - docker version
  - docker-compose version

script:
  - ./useful/install.sh "$SERVICE" "$TRAVIS_BRANCH"