# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethwallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('address',)]),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('hash',)]),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('hash',)]),
        ),
    ]
