# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethwallet', '0002_auto_20160517_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
