# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethwallet', '0003_address_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.IntegerField(),
        ),
    ]
