# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethwallet', '0004_auto_20160518_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=25),
        ),
    ]
