# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethwallet', '0005_auto_20160518_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
