# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethwallet', '0006_auto_20160522_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='webhook',
            field=models.CharField(max_length=110),
        ),
    ]
