__author__ = 'andrew.shvv@gmail.com'

from decimal import Decimal

NOTIFY_RETRY_COUNTDOWN = 10
NOTIFY_MAX_RETRIES = 100

SEND_RETRY_COUNTDOWN = 10
SEND_MAX_RETRIES = 100

MAX_DIGITS = 19
DECIMAL_PLACES = 12

OFFER_MAX_DIGITS = MAX_DIGITS + (MAX_DIGITS - DECIMAL_PLACES)
ACCOUNT_MAX_DIGITS = OFFER_MAX_DIGITS

AMOUNT_MIN_VALUE = Decimal(1 / 10 ** DECIMAL_PLACES)
PRICE_MIN_VALUE = Decimal(1 / 10 ** DECIMAL_PLACES)

CONFIRMATIONS_FOR_NOTIFICATION = 3

PASSWORD_ITERATIONS = 10000

ADDRESS_LEN = 50

API_KEY_LEN = 40
API_SECRETS_LEN = 40
WEBHOOK_LEN = 110
HASH_LEN = 100

NOTIFICATION_INIT = 0
NOTIFICATION_PENDING = 1
NOTIFICATION_DONE = 2
NOTIFICATION_FAILURE = 3

AVAILABLE_NOTIFICATIONS_STATUS = {
    'init': NOTIFICATION_INIT,
    'pending': NOTIFICATION_PENDING,
    'done': NOTIFICATION_DONE,
    'failure': NOTIFICATION_FAILURE
}

WEI_INT_ETH = 10 ** 18
