__author__ = 'andrew.shvv@gmail.com'

from decimal import Decimal

NOTIFY_RETRY_COUNTDOWN = 5
CELERY_MAX_RETRIES = 1000

MAX_DIGITS = 15
DECIMAL_PLACES = 8

OFFER_MAX_DIGITS = MAX_DIGITS + (MAX_DIGITS - DECIMAL_PLACES)
ACCOUNT_MAX_DIGITS = OFFER_MAX_DIGITS

AMOUNT_MIN_VALUE = float(Decimal("1") / (Decimal("10") ** DECIMAL_PLACES))
PRICE_MIN_VALUE = float(Decimal("1") / (Decimal("10") ** DECIMAL_PLACES))

CONFIRMATIONS_FOR_NOTIFICATION = 3
